const UserActionTypes = {
    
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    GOOGLE_LOGIN_START: 'GOOGLE_LOGIN_START',
    EMAIL_LOGIN_START: 'EMAIL_LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    USER_LOGOUT_START: 'USER_LOGOUT_START',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAIL: 'USER_LOGOUT_FAIL',

    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
};

export default UserActionTypes;